"""Some transformations and selected features"""
import pandas as pd


def select_features(df):
    """select features"""
    df = df.drop(columns=['HAPPINESS_RANK', 'YEAR'], axis=1)
    return df


def continent(df):
    """Transform countrys and region"""

    country_to_continent = {
        'Switzerland': 'EUROPE',
        'Iceland': 'EUROPE',
        'Denmark': 'EUROPE',
        'Norway': 'EUROPE',
        'Finland': 'EUROPE',
        'Netherlands': 'EUROPE',
        'Sweden': 'EUROPE',
        'Austria': 'EUROPE',
        'Luxembourg': 'EUROPE',
        'Ireland': 'EUROPE',
        'Belgium': 'EUROPE',
        'United Kingdom': 'EUROPE',
        'Germany': 'EUROPE',
        'France': 'EUROPE',
        'Czech Republic': 'EUROPE',
        'Spain': 'EUROPE',
        'Malta': 'EUROPE',
        'Slovakia': 'EUROPE',
        'Italy': 'EUROPE',
        'Moldova': 'EUROPE',
        'Slovenia': 'EUROPE',
        'Lithuania': 'EUROPE',
        'Russia': 'EUROPE',
        'North Cyprus': 'EUROPE',
        'Cyprus': 'EUROPE',
        'Kosovo': 'EUROPE',
        'Estonia': 'EUROPE',
        'Montenegro': 'EUROPE',
        'Romania': 'EUROPE',
        'Serbia': 'EUROPE',
        'Portugal': 'EUROPE',
        'Latvia': 'EUROPE',
        'Macedonia': 'EUROPE',
        'Albania': 'EUROPE',
        'Bosnia and Herzegovina': 'EUROPE',
        'Greece': 'EUROPE',
        'Hungary': 'EUROPE',
        'Bulgaria': 'EUROPE',
        'Turkey': 'ASIA',
        'Ukraine': 'EUROPE',
        'Belarus': 'EUROPE',
        'Croatia': 'EUROPE',
        'Poland': 'EUROPE',
        'North Macedonia': 'EUROPE',
        'Puerto Rico': 'NORTH AMERICA',
        'Canada': 'NORTH AMERICA',
        'Costa Rica': 'NORTH AMERICA',
        'Mexico': 'NORTH AMERICA',
        'United States': 'NORTH AMERICA',
        'Panama': 'NORTH AMERICA',
        'Trinidad and Tobago': 'NORTH AMERICA',
        'El Salvador': 'NORTH AMERICA',
        'Guatemala': 'NORTH AMERICA',
        'Nicaragua': 'NORTH AMERICA',
        'Jamaica': 'NORTH AMERICA',
        'Dominican Republic': 'NORTH AMERICA',
        'Honduras': 'NORTH AMERICA',
        'Haiti': 'NORTH AMERICA',
        'Brazil': 'SOUTH AMERICA',
        'Venezuela': 'SOUTH AMERICA',
        'Chile': 'SOUTH AMERICA',
        'Argentina': 'SOUTH AMERICA',
        'Uruguay': 'SOUTH AMERICA',
        'Colombia': 'SOUTH AMERICA',
        'Ecuador': 'SOUTH AMERICA',
        'Bolivia': 'SOUTH AMERICA',
        'Paraguay': 'SOUTH AMERICA',
        'Peru': 'SOUTH AMERICA',
        'Suriname': 'SOUTH AMERICA',
        'New Zealand': 'OCEANIA',
        'Australia': 'OCEANIA',
        'Israel': 'ASIA',
        'United Arab Emirates': 'ASIA',
        'Oman': 'ASIA',
        'Singapore': 'ASIA',
        'Qatar': 'ASIA',
        'Thailand': 'ASIA',
        'Saudi Arabia': 'ASIA',
        'Taiwan': 'ASIA',
        'Kuwait': 'ASIA',
        'Uzbekistan': 'ASIA',
        'Japan': 'ASIA',
        'South Korea': 'ASIA',
        'Bahrain': 'ASIA',
        'Kazakhstan': 'ASIA',
        'Malaysia': 'ASIA',
        'Turkmenistan': 'ASIA',
        'Hong Kong': 'ASIA',
        'Indonesia': 'ASIA',
        'Vietnam': 'ASIA',
        'Kyrgyzstan': 'ASIA',
        'Bhutan': 'ASIA',
        'Azerbaijan': 'ASIA',
        'Pakistan': 'ASIA',
        'Jordan': 'ASIA',
        'China': 'ASIA',
        'Philippines': 'ASIA',
        'Laos': 'ASIA',
        'Mongolia': 'ASIA',
        'Lebanon': 'ASIA',
        'Tajikistan': 'ASIA',
        'Palestinian Territories': 'ASIA',
        'Bangladesh': 'ASIA',
        'Iran': 'ASIA',
        'Iraq': 'ASIA',
        'India': 'ASIA',
        'Myanmar': 'ASIA',
        'Georgia': 'ASIA',
        'Sri Lanka': 'ASIA',
        'Yemen': 'ASIA',
        'Armenia': 'ASIA',
        'Cambodia': 'ASIA',
        'Afghanistan': 'ASIA',
        'Syria': 'ASIA',
        'Libya': 'AFRICA',
        'Mauritius': 'AFRICA',
        'Nigeria': 'AFRICA',
        'Zambia': 'AFRICA',
        'Somaliland region': 'AFRICA',
        'Morocco': 'AFRICA',
        'Mozambique': 'AFRICA',
        'Swaziland': 'AFRICA',
        'South Africa': 'AFRICA',
        'Ghana': 'AFRICA',
        'Zimbabwe': 'AFRICA',
        'Liberia': 'AFRICA',
        'Sudan': 'AFRICA',
        'Congo (Kinshasa)': 'AFRICA',
        'Ethiopia': 'AFRICA',
        'Sierra Leone': 'AFRICA',
        'Mauritania': 'AFRICA',
        'Kenya': 'AFRICA',
        'Djibouti': 'AFRICA',
        'Malawi': 'AFRICA',
        'Cameroon': 'AFRICA',
        'Egypt': 'AFRICA',
        'Angola': 'AFRICA',
        'Mali': 'AFRICA',
        'Congo (Brazzaville)': 'AFRICA',
        'Comoros': 'AFRICA',
        'Uganda': 'AFRICA',
        'Senegal': 'AFRICA',
        'Gabon': 'AFRICA',
        'Niger': 'AFRICA',
        'Tanzania': 'AFRICA',
        'Madagascar': 'AFRICA',
        'Central African Republic': 'AFRICA',
        'Chad': 'AFRICA',
        'Guinea': 'AFRICA',
        'Ivory Coast': 'AFRICA',
        'Burkina Faso': 'AFRICA',
        'Rwanda': 'AFRICA',
        'Benin': 'AFRICA',
        'Burundi': 'AFRICA',
        'Togo': 'AFRICA',
        'Namibia': 'AFRICA',
        'Algeria': 'AFRICA',
        'Belize': 'NORTH AMERICA',
        'Northern Cyprus': 'EUROPE',
        'Lesotho': 'AFRICA',
        'Botswana': 'AFRICA',
        'South Sudan': 'AFRICA',
        'Somalia': 'AFRICA',
        'Tunisia': 'AFRICA',
        'Nepal': 'ASIA',
        'Gambia': 'AFRICA',
        'Taiwan Province of China': 'ASIA',
        'Hong Kong S.A.R., China': 'ASIA',
        'Trinidad & Tobago': 'NORTH AMERICA'
    }
    df['CONTINENT'] = df['COUNTRY_OR_REGION'].map(country_to_continent)
    return df


def contients_dummies(df):
    """Conver continent into dummies"""
    df = pd.get_dummies(df, columns=['CONTINENT'], drop_first=True)
    df = df.drop(columns=['COUNTRY_OR_REGION'])
    df.replace({False: 0, True: 1}, inplace=True)
    return df


def standardize_columns(df):
    """standize columns"""
    df.columns = df.columns.str.replace(r'[^A-Za-z0-9_]+', '_', regex=True).str.upper()
    return df
